twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel
        timeout: 0.5
        priority: 10
      target_safety:
        topic: cmd_vel_safety
        timeout: 0.5
        priority: 100
